### ISSUE TITLE
Error en windows 7 x64 (boundaries)

### ISSUE THREAD

**Issue by rocknard** [D3fau4/NightLib#1]
Algo dicen por aquí: https://stackoverflow.com/questions/20940979/what-is-an-indexoutofrangeexception-argumentoutofrangeexception-and-how-do-i-f

`Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
at Internal.Runtime.CompilerHelpers.ThrowHelpers.ThrowIndexOutOfRangeException() + 0x24
at NightLib.CLI.Program.Main(String[]) + 0x163
at NightLib.CLI!<baseaddress>+0x7e2d1b`

Gracias.

**Comment by D3fau4** [comment]
Ese error lo da cuando no le pasas ningún parámetro al programa.
